[package]
name = "doomslug"
version = "0.1.0"
authors = ["Arun Sharma <arun@sharma-home.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sha2 = "0.9.3"
